config/routes.rb
Rails.application.routes.draw do
  root to: "questionnaires#index"
  resources :questionnaires do
    post "questions_assoc", "questions_assoc"
  end
  resources :questions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :questionnaire_questions
  has_many :questionnaires, through: :questionnaire_questions, dependent: :destroy
end

app/models/questionnaire.rb
class Questionnaire < ApplicationRecord
  has_many :questionnaire_questions, -> {order("position ASC")}
  has_many :questions, -> {order("position ASC")}, through: :questionnaire_questions, dependent: :destroy
end

app/models/questionnaire_question.rb
class QuestionnaireQuestion < ApplicationRecord
  belongs_to :question
  belongs_to :questionnaire

  acts_as_list :scope => :questionnaire
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  before_action :set_questionnaire, only: [:show, :edit, :update, :destroy]

  # GET /questionnaires
  # GET /questionnaires.json
  def index
    @questionnaires = Questionnaire.all
  end

  # GET /questionnaires/1
  # GET /questionnaires/1.json
  def show
    questions = Question.all
    @questionnaire_questions = @questionnaire.questions
    @remainning_questions = questions - @questionnaire_questions
  end

  # GET /questionnaires/new
  def new
    @questionnaire = Questionnaire.new
  end

  # GET /questionnaires/1/edit
  def edit
  end

  # POST /questionnaires
  # POST /questionnaires.json
  def create
    @questionnaire = Questionnaire.new(questionnaire_params)

    respond_to do |format|
      if @questionnaire.save
        format.html { redirect_to @questionnaire, notice: 'Questionnaire was successfully created.' }
        format.json { render :show, status: :created, location: @questionnaire }
      else
        format.html { render :new }
        format.json { render json: @questionnaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questionnaires/1
  # PATCH/PUT /questionnaires/1.json
  def update
    respond_to do |format|
      if @questionnaire.update(questionnaire_params)
        format.html { redirect_to @questionnaire, notice: 'Questionnaire was successfully updated.' }
        format.json { render :show, status: :ok, location: @questionnaire }
      else
        format.html { render :edit }
        format.json { render json: @questionnaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questionnaires/1
  # DELETE /questionnaires/1.json
  def destroy
    @questionnaire.destroy
    respond_to do |format|
      format.html { redirect_to questionnaires_url, notice: 'Questionnaire was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def questions_assoc
    @questionnaire = Questionnaire.find(params[:questionnaire_id])
    @questionnaire.questions = []
    questions = params[:questionnaire][:questions]
    questions.shift
    questions.each { |q| @questionnaire.questions << Question.find(q) }
    @questionnaire.save
    redirect_to questionnaires_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_questionnaire
      @questionnaire = Questionnaire.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def questionnaire_params
      params.require(:questionnaire).permit(:name)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:question)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questionnaires_helper.rb
module QuestionnairesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OrderedManyToMany</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav>
    <ul>
      <li><%= link_to "Questionnaires", questionnaires_url %></li>
      <li><%= link_to "Questionns", questions_url %></li>
    </ul>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/questionnaires/_form.html.erb
<%= form_with(model: questionnaire, local: true) do |form| %>
  <% if questionnaire.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(questionnaire.errors.count, "error") %> prohibited this questionnaire from being saved:</h2>

      <ul>
      <% questionnaire.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :questionnaire_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questionnaires/edit.html.erb
<h1>Editing Questionnaire</h1>

<%= render 'form', questionnaire: @questionnaire %>

<%= link_to 'Show', @questionnaire %> |
<%= link_to 'Back', questionnaires_path %>

app/views/questionnaires/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questionnaires</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questionnaires.each do |questionnaire| %>
      <tr>
        <td><%= questionnaire.name %></td>
        <td><%= link_to 'Show', questionnaire %></td>
        <td><%= link_to 'Edit', edit_questionnaire_path(questionnaire) %></td>
        <td><%= link_to 'Destroy', questionnaire, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Questionnaire', new_questionnaire_path %>

app/views/questionnaires/new.html.erb
<h1>New Questionnaire</h1>

<%= render 'form', questionnaire: @questionnaire %>

<%= link_to 'Back', questionnaires_path %>

app/views/questionnaires/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @questionnaire.name %>
</p>

<%= form_with(:model => Questionnaire, url: questionnaire_questions_assoc_path(@questionnaire)) do |f| %>

  <div class="left">
    <%= f.select(:no_assoc, @remainning_questions.map{ |item| [item.question, item.id] }, {}, {:multiple => true, :size => 10, :id => "no_assoc"}) %>
  </div>



  <div class="right">
    <%= f.select(:questions, @questionnaire_questions.map{ |item| [item.question, item.id] }, {}, {:multiple => true, :size => 10, :id => "assoc"}) %>
  </div>
  <div>
    <button class="controll" id="add_all">ADD ALL</button><br />
    <button class="controll" id="add">ADD</button><br />
    <button class="controll" id="remove">REMOVE</button><br />
    <button class="controll" id="remove_all">REMOVE ALL</button><br />
  </div>
  <div class="right">
    <button class="controll" id="up">UP</button>
    <button class="controll" id="down">DOWN</button>
  </div>

<% end %>
<div class="clear">
  <button id="send">SEND</button>
</div>


<%= link_to 'Edit', edit_questionnaire_path(@questionnaire) %> |
<%= link_to 'Back', questionnaires_path %>


<script type="text/javascript">
  $(document).ready(function(){
    $("#add_all").on("click", function(){
        $("select#no_assoc option").each(function(){
            $("select#assoc").append($('<option>',{value: $(this).attr("value"), text: $(this).html()}));
            $(this).remove();
        });
        return false;
    });
    $("#add").on("click", function(){
        $("select#no_assoc option:selected").each(function(){
            $("select#assoc").append($('<option>',{value: $(this).attr("value"), text: $(this).html()}));
            $(this).remove();
        });
        return false;
    });
    $("#remove").on("click", function(){
        $("select#assoc option:selected").each(function(){
            $("select#no_assoc").append($('<option>',{value: $(this).attr("value"), text: $(this).html()}));
            $(this).remove();
        });
        return false;
    });
    $("#remove_all").on("click", function(){
        $("select#assoc option").each(function(){
            $("select#no_assoc").append($('<option>',{value: $(this).attr("value"), text: $(this).html()}));
            $(this).remove();
        });
        return false;
    });
    $("button#send").on("click", function(){
        $("select#assoc option").each(function(){
            $(this).attr("selected", "selected");
        });
        $("form").submit();
    });

    $("button#up").on("click", function(){
      $("select#assoc option:selected").each(function(){
        var op = $(this);
        op.first().prev().before(op);
      });
      return false;
    });

    $("button#down").on("click", function(){
      $("select#assoc option:selected").each(function(){
        var op = $(this);
        op.first().next().after(op);
      });
      return false;
    });
  });
</script>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :question %>
    <%= form.text_field :question, id: :question_question %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.question %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @question.question %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>